- name: Change The Hostname
  hosts: all
  become: true
  tasks:
    - hostname:
        name: "{{ inventory_hostname }}"
      when: ansible_fqdn != ansible_ssh_host
      tags: ["hostname"]

- name: Commons Configurations
  hosts: all
  become: true
  roles:
    - role: commons
      tags: ["commons", 'all']

    - role: ansible-history
      tags: ["ansible-history", 'all']

    - role: bertvv.hosts
      tags: ["hosts", 'all']

    - role: geerlingguy.ntp
      tags: ["ntp", 'all']

    - role: softasap.sa-prometheus-exporters
      vars:
        - prometheus_exporters: "{{ box_prometheus_exporters }}"
      tags: ['prometheus-node-exporter', 'all']

- name: Configuring Prometheus
  hosts: prometheus
  become: true
  roles:
    - role: prometheus
      tags: ["prometheus"]

- name: Configuring Grafana
  hosts: grafana
  become: true
  roles:
    - role: grafana
      tags: ["grafana"]

- name: Configuring NATS Servers
  hosts: nats
  become: true
  roles:
    - role: nats
      tags: ['nats']

- name: Configuring NATS Streaming Servers
  hosts: streaming
  become: true
  roles:
    - role: nats-streaming
      tags: ['nats-streaming']

    - role: prometheus-nats-exporter
      tags: ['nats-streaming', 'prometheus-nats-exporter']
